controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# create an route
home:
    path: /home
    controller: App\Controller\HomeController::sayHello
