controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# create an route
home:
    path: /home
    controller: App\Controller\HomeController::sayHello

redirectToRoute:
    path: /redirecttoroute
    controller: App\Controller\HomeController::sayBye

redirectToLinkedin:
    path: /redirecttolinkedin
    controller: App\Controller\HomeController::redirecttolinkedin

showTemplate:
    path: /showtemplate
    controller: App\Controller\HomeController::showTemplate

products:
    path: /products
    controller: App\Controller\HomeController::showProducts
